### ISSUE TITLE
Future

### ISSUE THREAD

**Issue by papoteur-mga** [jjdejong/phpip-legacy#11]
Hello,
I'm interested by this application and will use it in the near future.
Which feature would you like to have some contribution?
I see some topic which would be useful:
- mail merging using date from cases or parties;
- managing the process of renewals (reminders, orders)
- billing;
- connection with other application like CRM/ERP to share the people/societies database, the offre/billing ...
  Papoteur

**Comment by jjdejong** [comment]
Hi Papoteur!

Thank you for your interest and offer to contribute. I yous ask me, I believe the most urgent is to develop a user management function, i.e. for adding/updating/deleting users, changing passwords, etc. Currently I do that with SQL scripts. Users are in the actor table but they are also cloned as mysql users to manage their permissions, which makes it a bit more complex.

Just start using the software and contribute the functionality you need most. Before doing so, check with me whether the functionality is not already available/planned and how we implement it. For instance, we already do mail merging, pretty extensively (through Word templates connecting directly to the database via ODBC) - it all depends on how you expect to do it. Processes are configurable ad infinitum - they are defined by the events and tasks you configure (you can set multiple tasks to auto-create at different dates for an event, and you can set conditions for the auto-creation). It is not all documented yet...

--JJJ

**Comment by papoteur-mga** [comment]
Hello JJJ
I will have a look to ad the feature to add users.
If  you have some general directive for that, perhaps can you expose them.
Papoteur.

**Comment by jjdejong** [comment]
Papoteur has contributed code for database user management. The code has been merged into the main branch.
