### ISSUE TITLE
Problème de saisie automatique des noms des acteurs

### ISSUE THREAD

**Issue by Omnipat** [jjdejong/phpip-legacy#12]
En voulant créer un « new matter », le champ "responsible" ne se remplit plus avec la saisie semi-automatique
Auparavant, je tapais les premières lettres de l'ingénieur en charge et phpIP me proposait les noms des acteurs correspondant. Cela n’est plus la cas

**Comment by jjdejong** [comment]
Fixed in commit 3f1f5e8805e421500b1c18a882787436e6b21755
