### ISSUE TITLE
Pb nouvelle installation 

### ISSUE THREAD

**Issue by southernnewbee** [jjdejong/phpip-legacy#16]
Après vérification de l’installation et essai sur l’installation faite, il apparait que le logiciel PHPIP édité sur github n’est pas complet. En effet, lors d’une installation suivant la procédure prescrite dans le wiki, je n’arrive pas à faire marcher la commande php artisan (que ce soit pour générer la clé de chiffrement ou se servir d’un serveur web local). Cette commande me retourne qu’il n’existe pas de fichiers dans un répertoire non fourni dans github. J’ai également créé un projet laravel (cms (comme wordpress) de phpip) vierge qui est fonctionnel. Dans ce projet vierge, il apparait un dossier vendor (demandé par artisan) absent de phpip-v2.
Pour essayer de résoudre le problème, j’ai, dans un premier temps, copié ce dossier dans le projet phpip. Dans ce cadre, artisan retourne une série d’erreurs ne trouvant pas certaines class. Dans un second temps, j’ai copié les fichiers spécifiques à phpip dans ce projet vierge. Malheureusement, malgré le non impact sur artisan (toujours opérationnel), la page qui s’affiche est toujours la page par défaut de laravel.
De plus, la version 1 de phpip n’est plus opérationnel (également testé). 

Avez vous une une procédure d’installation en partant d’un projet laravel vierge ?

Merci

**Comment by papoteur-mga** [comment]
Bonjour,
Merci de votre intérêt pour phpIP.
Tout retour sera intéressant. 
La version opérationnelle est la version 1. Phpip-v2 est en cours de développement.
Pour la v2, avez-vous exécuté la commande composer update ? De mémoire, c'est cette commande qui complète le dossier vendor.

**Comment by jjdejong** [comment]
Nous sommes dans les incidents de la v1 ici. Il aurait fallu poster ceci dans les incidents de la v2.

Je confirme que la v2 n'est pas encore opérationnelle. Pour la tester, il faut consulter le [wiki de la v2](https://github.com/jjdejong/phpip-v2#to-get-going). Il n'y a pas de procédure à partir d'un projet Laravel vierge, mais on devrait pouvoir copier le dossier "vendor" d'un projet vierge dans le projet phpip-v2.

En quoi la v1 n'est pas opérationnelle ? Il faudrait nous en dire plus.

**Comment by southernnewbee** [comment]
Merci pour vos réponses.
J’ai réinstallé la version 1 de PHPIP suite à la confirmation que la version 2 est en Béta. Suite à un crash serveur et une sauvegarde ancienne de la base de données, j’ai récupéré la base de données actuelle via les fichiers de mysql. Il apparait que certaines fiches soient figées (c’est-à-dire non modifiables). Suite à l’importation de la base puis à l’application de la dernière mise à jour (de la BDD), le soucis demeure. Je pense que le soucis provient de la base de données. J’aimerai savoir si il existe une procédure ou un script permettant de remettre la BDD en ordre.

Merci !

**Comment by jjdejong** [comment]
Vous êtes en train de dire que vous avez utilisé le script de migration de base vers la v2 sur une base v1 qui était en production ? Et que vous n'aviez pas de sauvegarde de la base v1 ?

Expliquez-nous pas par pas les opérations que vous avez faites sur la base et les sauvegardes que vous avez de la dernière base opérationnelle.

**Comment by southernnewbee** [comment]
Le crash serveur n'est pas lié à la version 2 de PHPIP. Suite à une mise à jour d'Ubuntu, le serveur est tombé. Les fichiers racines ont été déplacés dans un dossier donc pas à la racine. Suite à cela, j'ai récupéré les fichiers MySQL qui se trouvent dans /var/lib/MySQL. Par ailleurs, j'ai installé un serveur wamp avec phpmyadmin. A partir de là, j'ai récupéré l'archive .sql via phpmyadmin de la base PHPIP. Ensuite, j'ai importé cette archive dans la nouvelle installation. Ensuite, j'ai appliqué le dernier script de mise à jour de la version 1.

**Comment by jjdejong** [comment]
Alors ce n'est pas un bug, mais une mauvaise manipulation quelquepart. Qu'est-ce qui ne fonctionne pas ? Listez les opérations et les messages d'erreur. Il faut être explicite.

S'agit-il d'une base de production ? Sinon, vous pouvez repartir de zéro à partir du script "squelette" pour créer la base, en omettant la création des utilisateurs s'ils y sont déjà.
