### ISSUE TITLE
Nouveau problème avec Evenement Depot

### ISSUE THREAD

**Issue by alexandreIP** [jjdejong/phpip-legacy#17]
Bonjour,
je viens de réinstaller toute ma base au "propre"  et vierge.
Je n'arrive pas à saisir l'évènement "filed" alors que tous les autres semblent fonctionner.

Le message d'erreur reçu est le suivant: 
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`phpip`.`task`, CONSTRAINT `fk_assigned_to` FOREIGN KEY (`assigned_to`) REFERENCES `actor` (`login`) ON DELETE SET NULL ON UPDATE CASCADE), query was: INSERT INTO `event` (`matter_ID`, `code`, `event_date`, `alt_matter_ID`) VALUES (?, ?, ?, ?)

Merci de votre réponse
Bien cordialement,
Alexandre

**Comment by jjdejong** [comment]
Il semblerait qu'il manque un utilisateur à qui une tâche doit être attribuée par défaut. Que contient la table "default_actor" ?

**Comment by alexandreIP** [comment]
Bonsoir,
j'ai un peu poursuivi les tests:
Impossible de créer l'évènement pour un dossier vierge "France" ou "EPO"
mais cela est au moins possible pour un dossier "Belge" ou "United Arab
Emirates"

La table "default_actor" semble vide !

Ai-je mal exécuté le script ?

Bonne soirée,

**Comment by jjdejong** [comment]
Est-ce qu'il y a des valeurs autres que NULL dans la colonne "default_responsible" de la table "event_name" ? Si oui, il faut y mettre NULL (à moins que la valeur soit le login d'un acteur présent dans la table "actor"). Il se peut que vous n'ayez pas exécuté la denière version du script de création de la base.

**Comment by alexandreIP** [comment]
Bonjour,
la colonne  "default_responsible" de la table "event_name" ne contient que
des valeurs NULL.
Je confirme que la table "default_actor" ne comporte aucune enregistrement
(aucune ligne)
Merci

**Comment by jjdejong** [comment]
J'ai pu reproduire l'erreur. Il s'agissait de la présence de la valeur 'root' dans le champ "default_responsible" dans la table "event_name", pour la rangée code='REN'. Assurez-vous bien que cette colonne ne contienne que des valeurs NULL. Je corrige le script de création de la base.

**Comment by alexandreIP** [comment]
C'est bien cela, bug résolu !
Je n'avais pas vu cette valeur...
Merci
