### ISSUE TITLE
suppression d'annuités

### ISSUE THREAD

**Issue by alexandreIP** [jjdejong/phpip-legacy#19]
Bonjour,
lorsque je cherche à supprimer une annuité, j'ai un message d'erreur qui apparaît après avoir cliqué sur la croix. Pour autant, l'annuité est bien supprimée.

Voici le contenu du message:
Warning: Invalid argument supplied for foreach() in /Applications/MAMP/htdocs/phpip/application/views/scripts/matter/tasklist.phtml on line 393.

**Comment by jjdejong** [comment]
Un bug ! C'est réparé dans le dernier commit.

**Comment by alexandreIP** [comment]
En effet, merci !

**Comment by jjdejong** [comment]
Il semblerait que j'aie maintenant cassé la liste de tâches normale.
