### ISSUE TITLE
Error when entering a filed event in TM matter

### ISSUE THREAD

**Issue by papoteur-mga** [jjdejong/phpip-legacy#21]
I enter an event "Filed" in a TM matter.
I get:
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`phpip`.`task`, CONSTRAINT `fk_assigned_to` FOREIGN KEY (`assigned_to`) REFERENCES `actor` (`login`) ON DELETE SET NULL ON UPDATE CASCADE), query was: INSERT INTO `event` (`matter_ID`, `code`, `event_date`, `detail`, `alt_matter_ID`) VALUES (?, ?, ?, ?, ?)
This is not the case with PAT matters.

**Comment by jjdejong** [comment]
Check if the corresponding task rule has a "responsible" value that is null or is a login in the actor table. The "assigned_to" field of the task receives this value.

**Comment by papoteur-mga** [comment]
Yes, good catch, JJJ.
For some rules, the field contains the **string** "NULL" instead of being NULL :(
Thus, some check to do with the creation of the database, I think.

**Comment by papoteur-mga** [comment]
This was coming from an old skeleton. 
Solved by setting all rules with NULL instead of 'NULL'
Thanks
