### ISSUE TITLE
NGINX -- Zend application in index.php is 'echoing' commands

### ISSUE THREAD

**Issue by srdco** [jjdejong/phpip-legacy#22]
Installed a fresh copy manually in a subdirectory of /var/www, linked to a dedicated subdomain.
Setup NGINX accordingly -- nginx is loading index.php, but index.php is just printing out all commands after `$application->`.
[Site can be seen here.](https://ipdocket.solidrock.enterprises)

I have a copy running well on Apache2 on a local-only server, but was working on setting up a public server. The server runs NGINX, and I don't see any particular reason it shouldn't work under NGINX.
That said ... this doesn't really seem like an NGINX problem, but I'm not familiar at all with the ZEND framework. E.g. ... I'm not sure where index.php finds the 'Zend/Application.php' file, since it's not in the 'public' folder?

Any ideas?
Thanks!

**Comment by papoteur-mga** [comment]
Hello,
You have to install Zend, which is not provided with the tarball.
See: https://github.com/jjdejong/phpip/wiki/Installing#12-zend-framework-12
Know that Zend Framework 1 is no more maintained.

**Comment by srdco** [comment]
Sorry -- I forgot to specify that Zend framework is installed using the zendframework package.
Any ideas on why it is just echoing as soon as the application object is used?

**Comment by jjdejong** [comment]
Probably PHP not configured to include the Zend libraries in php.ini. What is your distro?

**Comment by srdco** [comment]
Ubuntu 18.10

**Comment by srdco** [comment]
PHP 7.3 is the active version, with fastcgi

**Comment by jjdejong** [comment]
That is rather cutting edge for a server. Can't help you much there, because we're using 18.04 or lower, with Apache. If you don't use the same configuration as us, you'll be pretty much on your own... Did you install zendframework 1.12 with apt? That's all there is to it with Apache (but you need to restart Apache). No idea with Nginx.

**Comment by srdco** [comment]
Sorry .. Meant Ubuntu 18.04.
Yes, installed zendframework 1.12 with apt.
Not sure if there's a problem with the active version of php not loading it ... maybe tied to an older version still on the server.
I'll look into it --- thanks for the help.

**Comment by jjdejong** [comment]
Why would you want to use PHP 7.3? If you stick to a standard Bionic installation, I believe it should work out of the box.

**Comment by srdco** [comment]
Finally came back to this ... 
NGINX requires that the Zend commands be 'passed through' ...

    location ~ \.php$ {
        try_files $uri index.php =404;
        fastcgi_pass unix:/var/run/php/php7.3-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

Something like this works to bring up the main page, at least. Still working out a 404 error on anything but index.php.

**Comment by srdco** [comment]
```
    location ~ \.css$ {
        try_files $uri =404;
    }

location / {
        try_files $uri $uri/ /index.php =404;
        fastcgi_pass unix:/var/run/php/php7.3-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
#       fastcgi_param SCRIPT_FILENAME /var/www/html/phpip/application/views/scripts$fastcgi_script_name;
#       fastcgi_param SCRIPT_NAME /index.php;
#        fastcgi_param QUERY_STRING q=$uri&$args;
        include fastcgi_params;
}

```

**Comment by srdco** [comment]
This serves everything but the matter summary pages. I can pull up the individual matters, I can load actors, users, etc. I can login & logout.
BUT ... if you click on Matter --> any link, then it just loads "Application Error"
I tried to convert the .htaccess -- that's what the `try_files $uri $uri/ /index.php =404;` is for: 1) try the URL, 2) try if it's a directory, 3) try index.php, 4) throw a 404 error.

I'm not quite sure how the Matters pages work differently than the Tables, etc. pages -- any clues that might unravel this? I believe it is a simple matter of redirection / rewriting not quite right.

**Comment by jjdejong** [comment]
V2 is ready now and we are dropping development of v1. Note that Zend framework 1 is very old and unsupported, so it may not play well with newer Linux distros. Why don't you try V2 now? This should at least fix all the Zend framework related issues. Do you have a large production base in v1? Make sure you follow all the steps of the Wiki (https://github.com/jjdejong/phpip-v2/wiki)

**Comment by srdco** [comment]
Done. That works. Thank you!
